Changes in the format of test cases.
ridi/lightweight-rest-tester pull request #12
Opened 2017-08-24 07:51 UTC by jihungen

I change the test case format since the original one does not reflect REST API. This is an example of new format:

```json
{
  "api": {
    "url": "http://json-server:3000/comments",
    "method": "get",
    "params": {
      "postId": 1
    }
  },
  "tests": {
    "timeout" : 10,
    "statusCode": 200
  }
}
```

And, for **Write-and-Read** tests, I let test cases to have the list of `api`/`tests` pairs:

```json
[
  {
    "api": {
      "url": "http://json-server:3000/posts",
      "method": "post",
      "data": {
        "title": "foo",
        "body": "bar",
        "userId": 1
      }
    },
    "tests": {
      "statusCode": 201
    }
  },
  {
    "api": {
      "url": "http://json-server:3000/posts",
      "method": "get",
      "params": {
        "userId": 1
      }
    },
    "tests": {
      "statusCode": 200
    }
  }
]
```

There are a lot of changes to reflect these changes on unit tests and README.

2017-08-24 08:16 UTC, migom commented
지금 하던 업무에 막히는 부분이 있어서 
마침맞게 딱 시간이 비었는데... 리뷰 초대해 주셔서 감사합니다. ㅋㅋㅋ

2017-08-24 08:17 UTC, jihungen commented
@migom 제가 감사하죠 ㅋ

2017-08-25 00:17 UTC, migom commented on README.md
> +The `api` part consists of `method`, `url`, `params` and `data`. `method` and `url` are essential, but `params` and `data` are optional.
json 코드에서 url, method, params, data 의 순서가 중요할 것 같진 않지만, 그래도 대부분(?)의 json 예제가 이 순서로 작성되어 있으니 ...
여기도 동일한 순서로 맞춰주면 보기 좋을 것 같습니다.^^

2017-08-25 00:42 UTC, migom commented on README.md
url, method 에 대한 설명도 있으면 좋을 것 같습니다.^^

#### url

- https://ko.wikipedia.org/wiki/HTTP 이 페이지의 클라이언트 요청 json 예제에 "url" 이 아니라 "uri" 로 되어 있길래 찾아보니 요즘은 uri 로 쓴다고 하네용? (https://blog.lael.be/post/61)
- 하지만, 별로 안 중요한 내용이니 무시하셔도 좋습니다~ㅎㅎ

#### method

- https://ko.wikipedia.org/wiki/HTTP
HTTP 메소드가 9개나 되는 줄 검색해 보고 알았네요~ㅎㅎ(저는 5개만 있는줄 알았어요...)
이 중에 어떤 어떤 메소드를 지원하는지를 알려주는 것도 좋을 것 같습니다.
"method": "get",
"method": "put",
...

2017-08-25 00:58 UTC, jihungen commented on README.md
> +The `api` part consists of `method`, `url`, `params` and `data`. `method` and `url` are essential, but `params` and `data` are optional.
넵

2017-08-25 01:00 UTC, jihungen commented on README.md
> +The `api` part consists of `method`, `url`, `params` and `data`. `method` and `url` are essential, but `params` and `data` are optional.
넵. essential하고 optional을 나눠놨는데, 지키는 한에서 순서를 바꾸겠습니다.

2017-08-25 01:09 UTC, jihungen commented on README.md
`url`은 딱히 쓸 부분이 없어서 그냥 놔뒀습니다. `uri`와 관련해서 CTO님이랑도 얘기를 해봤는데, `url`이 더 직관적일 것 같아서 `url`로 나뒀습니다.

HTTP method는 위에서도 설명해서 중복이 될 것 같아서 뺐는데, 넣겠습니다 :) Restful API를 지원하는 method는 전에 얘기하셨던 것처럼 보통 5가지로 알고 있습니다:
http://www.restapitutorial.com/lessons/httpmethods.html

2017-08-25 01:29 UTC, mskims commented on rest_tester/function/__init__.py
>      def build(self):
metaclass 와 `abc.abstractmethod` 데코레이터가 필요하지 않나요?

2017-08-25 01:29 UTC, mskims commented on rest_tester/function/fail.py
> +        TestFunctionBuilder.__init__(self, name_prefix)
`super(FailTestFunctionBuilder, self).__init__(name_prefix)` 와 차이가 있는건가요?

2017-08-25 01:43 UTC, mskims commented on rest_tester/setting/target.py
> +            raise IncompleteTargetInformationError('Test case has incomplete information.')
이것만 보면 어떤 Key 에서 오류가 났는지 알 수 없을것 같은데, 오류가 발생한 Key 이름 같은걸 알려줬으면 좋겠습니다.

2017-08-25 01:52 UTC, jihungen commented on rest_tester/function/fail.py
> +        TestFunctionBuilder.__init__(self, name_prefix)
저는 이걸 참조했는데, 어느게 더 나은지 모르겠네요;;
https://stackoverflow.com/questions/1385759/should-init-call-the-parent-classs-init

2017-08-25 01:52 UTC, jihungen commented on rest_tester/setting/target.py
> +            raise IncompleteTargetInformationError('Test case has incomplete information.')
넵

2017-08-25 01:53 UTC, jihungen commented on rest_tester/function/__init__.py
>      def build(self):
안 써줘도 동작의 문제는 없는데, 명시적으로 써주는게 맞는 것 같습니다!

2017-08-25 02:07 UTC, kim-hyeoncheol commented on rest_tester/function/fail.py
> +        TestFunctionBuilder.__init__(self, name_prefix)
http://blog.eairship.kr/286
2. 다중 상속
의 내용을 보시면 차이를 아실 수 있을 겁니다.^^

2017-08-25 02:14 UTC, jihungen commented on rest_tester/function/fail.py
> +        TestFunctionBuilder.__init__(self, name_prefix)
감사합니다!
여기는 다중상속을 안 하지만, 지금 다중상속을 쓰고 있는 다른 PR에서 써야할 테크닉이네요 ㅋㅋㅋㅋ 참고해서 고쳐야겠습니다.

2017-08-25 05:17 UTC, kim-hyeoncheol requested changes
민석님께서 의견주신,
"오류 메세지에, 오류가 발생한 Key 이름 같은 정보가 포함되어 있으면 좋겠습니다."
에 공감하는 뜻으로 Request changes 눌렀습니다.^^

2017-08-25 05:30 UTC, mskims requested changes
앗 그럼 저도 눌러야겠네요 ㅋㅋ

2017-08-25 05:38 UTC, jihungen commented
말씀하신 부분들 반영하고 다시 열겠습니다!

2017-08-28 05:29 UTC, migom commented on rest_tester/function/__init__.py
> +from rest_tester.setting import ParameterSet, TestMethod, UnsupportedMethodError
요게 혹시...
PyCharm 의 Code > Optimize Imports 기능에 의해 순서가 바뀐건가요?
(그냥 궁금해서요~~^^)

2017-08-28 05:30 UTC, mskims approved these changes

2017-08-28 05:32 UTC, jihungen commented on rest_tester/function/__init__.py
> +from rest_tester.setting import ParameterSet, TestMethod, UnsupportedMethodError
아니요, 제가 작업을 하다보니 이렇게 된 것 같습니다 ㅋ

2017-08-28 06:01 UTC, migom commented on run_test.sh
> +while ! docker ps | grep json-server | grep healthy; do
몇 일 전에 슬랙에서 비슷한걸 본 것 같은데...
이렇게 하면 unhealthy 도 잡힌다고 하지 않았나요?

2017-08-28 06:22 UTC, jihungen commented on run_test.sh
> +while ! docker ps | grep json-server | grep healthy; do
네 ㅋ 이거 수정하겠습니다!

2017-08-28 06:28 UTC, jihungen commented on run_test.sh
> +while ! docker ps | grep json-server | grep healthy; do
반영했습니다!

2017-08-28 06:55 UTC, kim-hyeoncheol approved these changes

2017-08-28 06:55 UTC, merged