Update README.md
ridi/lightweight-rest-tester pull request #5
Opened 2017-07-25 08:47 UTC by jihungen

Update README.md.

2017-07-25 08:48 UTC, jihungen commented
`Files changed`의 README.md 파일을 보실 때,
`Unified` 상태에서, `Display the rich diff`를 선택하시면, README의 preview를 보실 수 있습니다 :)

2017-07-25 09:28 UTC, mskims approved these changes

2017-07-25 09:30 UTC, mskims requested changes

2017-07-25 09:30 UTC, mskims commented on README.md
> +python rest_tester/main.py "JSON file directory"
clone 을 받아서 사용할 프로젝트에 Integrate 하는 과정도 있었으면 좋겠습니다.

2017-07-25 10:00 UTC, jihungen commented on README.md
> +python rest_tester/main.py "JSON file directory"
version 2.0에서 하는걸로... ㅋㅋㅋㅋ
issue에 올려주세요!

2017-07-25 10:01 UTC, mskims approved these changes

2017-07-25 23:47 UTC, migom commented on README.md
> +A lightweight REST API testing framework written in Python (working with 2.7 ~ 3.6). It reads test cases from JSON files and then generates and executes unittest of Python. It supports five HTTP meth
UPDATE -> PATCH ? 😄

2017-07-26 01:02 UTC, jihungen commented on README.md
> +A lightweight REST API testing framework written in Python (working with 2.7 ~ 3.6). It reads test cases from JSON files and then generates and executes unittest of Python. It supports five HTTP meth
네, 말씀하신 PATCH가 맞는 것으로 확인했습니다 :) 수정하겠습니다!

2017-07-26 01:14 UTC, kim-hyeoncheol approved these changes

2017-07-26 01:27 UTC, namenu commented on README.md
> +A lightweight REST API testing framework written in Python (working with 2.7 ~ 3.6). It reads test cases from JSON files and then generates and executes unittest of Python. It supports five HTTP meth
- 마지막 문장 (It supports~) 은 "JSON File Format" 섹션으로 옮기면 좋을 것 같습니다.
- JSON Schema 라는 키워드가 있으면 좋을 듯 합니다.

2017-07-26 01:59 UTC, curry-ing approved these changes

2017-07-26 03:45 UTC, iamchanu approved these changes

2017-07-26 06:07 UTC, jihungen commented on README.md
> +A lightweight REST API testing framework written in Python (working with 2.7 ~ 3.6). It reads test cases from JSON files and then generates and executes unittest of Python. It supports five HTTP meth
@namenu 반영했습니다!

2017-07-26 06:16 UTC, namenu approved these changes

2017-07-26 06:16 UTC, merged